---
- name: ensure package is installed
  package:
    name: ssmtp

- name: ensure esmtp is removed
  package:
    name: esmtp
    state: absent

- name: ensure configuration is in place
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
    owner: root
    group: mail
    mode: 0640
