---
- name: ensure ssmtp software is installed
  package:
    name: ssmtp

- name: ensure ssmtp is configured
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
    owner: root
    group: mail
    mode: 0640
